#!/usr/bin/env bash

# Easier Navigation
alias cd..="cd .."
alias cd...="cd ../.."
alias cd....="cd ../../.."
alias ..="cd .."
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

# Better list
alias ls="ls -CF"
alias lsa="ls -a -CF"

# Better clear
alias c='clear'

# IP
alias ipi='ipconfig getifaddr en0'
alias ipe='curl ipinfo.io/ip'

# Speedtest
alias speed='speedtest-cli --server 2406 --simple'

# Shortcuts
alias 280="cd /Users/aidanloughney/Code/eecs280"
alias 281="cd /Users/aidanloughney/Code/eecs281"
alias 370="cd /Users/aidanloughney/Code/eecs370"
alias 390="cd /Users/aidanloughney/Code/eecs390"
alias 449="cd /Users/aidanloughney/Code/eecs449"
alias 485="cd /Users/aidanloughney/Code/eecs485"
alias 493="cd /Users/aidanloughney/Code/eecs493"
