#!/usr/bin/env bash

# Easier Navigation
alias cd..="cd .."
alias cd...="cd ../.."
alias cd....="cd ../../.."
alias ..="cd .."
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

# Better list
alias ls="ls -CF"
alias lsa="ls -a -CF"

# Better clear
alias c='clear'

# IP
alias ipi='ipconfig getifaddr en0'
alias ipe='curl ipinfo.io/ip'

# Speedtest
alias speed='speedtest-cli --server 2406 --simple'
