#!/usr/bin/env bash

# Easier Navigation
alias cd..="cd .."
alias cd...="cd ../.."
alias cd....="cd ../../.."
alias ..="cd .."
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

# Better list
alias ls="ls -CF"
alias lsa="ls -aCF"
alias lsd="ls -d */"

# Better cat
alias cat="bat"

# Better clear
alias c='clear'

# IP
alias ipi='ipconfig getifaddr en0'
alias ipe='curl ipinfo.io/ip'

# Speedtest
alias speed='speedtest-cli --server 2406 --simple'

# git aliases (should match .gitconfig)
alias g='git'
alias ga='git add'
alias gp='git push'
alias gl='git pull'
alias gst='git status'
alias glg="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
alias gcm='git commit -m'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gd='git diff'
alias gdmr='diff master...HEAD'
alias gski='stash --keep-index'
